---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-alpine
inputs:
- name: source-code
outputs:
- name: artifact
run:
  path: sh
  args:
  - -exc
  - |
    cd source-code \
    && ./mvnw package -Dmaven.test.skip=true \
    && mv target/spring-boot-jpa*.jar ../artifact/spring-boot-jpa.jar
